CREATE DATABASE IF NOW EXISTS Restoran;
USE Restoran;

CREATE TABLE IF NOT EXISTS Customers(
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100),
    phone VARCHAR (15) UNIQUE,
);
CREATE TABLE IF NOT EXISTS Orders(
    id INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES Customers(id)
    order_data DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_price DECIMAL(10,2),
);

CREATE TABLE IF NOT EXISTS Customers(
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100),
    phone VARCHAR (15) UNIQUE,
);

CREATE TABLE IF NOT EXISTS Customers(
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100),
    phone VARCHAR (15) UNIQUE,
);