CREATE DATABASE IF NOW EXISTS Restoran;
USE Restoran;

CREATE TABLE IF NOT EXISTS Customers(
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100),
    phone VARCHAR (15) UNIQUE,
);
CREATE TABLE IF NOT EXISTS Orders(
    id INT AUTO_INCREMENT PRIMARY KEY,
    customer_id INT,
    order_data DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_price DECIMAL(10,2) NOT NULL
    FOREIGN KEY (customer_id) REFERENCES Customers(id),
);

CREATE TABLE IF NOT EXISTS Menu(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) UNIQUE,
    price DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS Order_Items(
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT,
    menu_id INT,
    FOREIGN KEY (order_id) REFERENCES Orders(id),
    FOREIGN KEY (menu_id) REFERENCES Menu(id),
    quantity INT
);