SELECT * FROM STUDENTS WHERE group_name='Group A';
SELECT * FROM STUDENTS WHERE age > 20 AND groupname = 'Group A';
SELECT * FROM STUDENTS WHERE groupname = 'Group B' OR groupname = 'Group C';
SELECT * FROM STUDENTS WHERE age>20;
SELECT * FROM STUDENTS WHERE age BETWEEN 19 AND 22;
SELECT * FROM STUDENTS WHERE groupname IN ('Group A', 'Group C');
SELECT * FROM STUDENTS WHERE name LIKE 'A%';
SELECT * FROM STUDENTS WHERE name LIKE '%li%';